version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0
        environment:
          - TFL_APP_KEY: test-tfl-app-key
          - TFL_APP_ID: test-tfl-app-id
          - TFL_APP_BASE: https://api.tfl.gov.uk
          - CC_TEST_REPORTER_ID: 4c515aa8be6aa66df39ae25db619d60a7b8a2c9241940100c480d7271a787abe
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Configure bundler
          command: bundle config set path 'vendor/bundle'
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - ruby/bundle-install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Code Climate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run the tests
          command: ./cc-test-reporter before-build && bundle exec rspec
      - store_artifacts:
          path: coverage
      - run:
          name: Format coverage
          command: ./cc-test-reporter format-coverage -t simplecov coverage/.last_run.json
      - run:
          name: Upload coverage
          command: ./cc-test-reporter upload-coverage
