---
http_interactions:
- request:
    method: get
    uri: https://api.tfl.gov.uk/Cabwise/search?app_id=TFL_APP_ID&app_key=TFL_APP_KEY&lat=bar&lon=foo
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Host:
      - api.tfl.gov.uk
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Date:
      - Tue, 18 Apr 2017 16:18:59 GMT
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '317'
      Connection:
      - keep-alive
      Set-Cookie:
      - __cfduid=dadadeea25d2c660040c812b9e06cd8a71492532339; expires=Wed, 18-Apr-18
        16:18:59 GMT; path=/; domain=.tfl.gov.uk; HttpOnly
      Access-Control-Allow-Headers:
      - Content-Type
      Access-Control-Allow-Methods:
      - GET,POST,PUT,DELETE,OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Age:
      - '0'
      Api-Entity-Payload:
      - Place
      Cache-Control:
      - public, must-revalidate, max-age=30, s-maxage=60
      Via:
      - 1.1 varnish
      X-Aspnet-Version:
      - 4.0.30319
      X-Backend:
      - api
      X-Banning:
      - ''
      X-Cache:
      - MISS
      X-Cacheable:
      - Yes. Cacheable
      X-Ttl:
      - '10.000'
      X-Ttl-Rule:
      - '0'
      X-Varnish:
      - '976052075'
      Server:
      - cloudflare-nginx
      Cf-Ray:
      - 3518f173ceec3482-LHR
    body:
      encoding: ASCII-8BIT
      string: '{"$type":"System.Web.Http.HttpError, System.Web.Http","message":"The
        request is invalid.","messageDetail":"The parameters dictionary contains a
        null entry for parameter ''lat'' of non-nullable type ''System.Double'' for
        method ''System.Net.Http.HttpResponseMessage Get(Double, Double, System.String,
        System.String, Double, System.String, System.Nullable`1[System.Int32], Boolean,
        Boolean, Boolean)'' in ''Tfl.Api.Presentation.PublicApi.Controllers.CabwiseController''.
        An optional parameter must be a reference type, a nullable type, or be declared
        as an optional parameter."}'
    http_version: 
  recorded_at: Tue, 18 Apr 2017 16:18:58 GMT
recorded_with: VCR 3.0.3
